name: .NET

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --configuration "Release" --framework "net6.0" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained False
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    - name: Zip folder
      run: zip -r -j folder.zip /home/runner/work/lambda_foursix/lambda_foursix/foursix-lambda/src/FourSix.Lambda.Authentication/bin/Release/net6.0/linux-x64/publish/
    - name: List Files
      run: ls
    - name: Install AWS CLI
      run: |
        sudo apt-get install python3-pip
        pip3 install awscli --upgrade --user
    - name: Configure AWS Credentials
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region us-east-1
    - name: Deploy Lambda
      run:  aws lambda update-function-code --function-name FourSixStack-AspNetCoreFunction-ykOM8E3tv9yQ --zip-file fileb://folder.zip